### ISSUE TITLE
Custom request/response schema class names

### ISSUE THREAD

**Issue by evstratbg** [Ovsyanka83/pydantic-duality#3]
Im using FastAPI and I need to name my request and response schemas in a certain way

It would be cool if I can define either prefix or/and suffix of a request/response schema or define the class name (because FastApi uses class name as a schema name in openapi) on schema generation

**Comment by zmievsa** [comment]
@evstratbg Ready for your review: https://github.com/Ovsyanka83/pydantic-duality/pull/4

See if that solves your problem and check whether the new base class and method names are to your liking.

No need to review the whole thing if you do not want to but definitely take a look at naming tests.

**Comment by evstratbg** [comment]
Looks legit. Any related info in README?

**Comment by zmievsa** [comment]
Completely forgot about README. On it.
